[[pages]]
path = "app.py"
name = "ì—…ë¬´í˜„í™©"
icon = "ğŸ“‹"

[[pages]]
path = "pages/1_ê³µì§€ì‚¬í•­.py"
name = "ê³µì§€ì‚¬í•­"
icon = "ğŸ“¢"

[[pages]]
path = "pages/2_ìë£Œì‹¤.py"
name = "ìë£Œì‹¤"
icon = "ğŸ“š"

[[pages]]
path = "pages/3_ìƒí’ˆê´€ë¦¬.py"
name = "ìƒí’ˆê´€ë¦¬"
icon = "ğŸ“¦"

[[pages]]
path = "pages/4_ë§ˆì´í˜ì´ì§€.py"
name = "ë§ˆì´í˜ì´ì§€"
icon = "ğŸ‘¤"

[[pages]]
path = "pages/5_ê´€ë¦¬ìì„¤ì •.py"
name = "ê´€ë¦¬ìì„¤ì •"
icon = "âš™ï¸"
